/* Generated By:JJTree: Do not edit this line. XPathCastableExpr.java */

package dongfang.xsltools.xpath2;

public class XPathCastableExpr extends XPathBase implements XPathExpr {
  public XPathCastableExpr(int id) {
    super(id);
  }

  public XPathCastableExpr(XPathParser p, int id) {
    super(p, id);
  }

  public short getType() {
    return TYPE_BOOLEAN; // TODO: right??
  }

  @Override
public String toString() {
    String res = jjtGetChild(0).toString();
    if (jjtGetNumChildren() > 1) {
      res += " castable as " + jjtGetChild(1).toString();
    }
    return res;
  }
}
