/* Generated By:JJTree: Do not edit this line. XPathSimpleForClause2.java */

package dongfang.xsltools.xpath2;

import dongfang.xsltools.exceptions.XSLToolsException;

public class XPathSimpleForClause2 extends XPathTempQName {
  public XPathSimpleForClause2(int id) {
    super(id);
  }

  public XPathSimpleForClause2(XPathParser p, int id) {
    super(p, id);
  }

  /*
   * This clause introduces locally scoped variables. Some visitors want to know
   * about that, so we accept them explicitly.
   */
  @Override
  public XPathBase accept(XPathVisitor v) throws XSLToolsException {
    return v.visit(this);
  }

  @Override
public String toString() {
    StringBuilder res = new StringBuilder();
    res.append(", $");
    res.append(qname.getQualifiedName());
    res.append(" in ");
    res.append(jjtGetChild(0).toString());
    return res.toString();
  }
}
