/* Generated By:JJTree: Do not edit this line. XPathItemTest.java */

package dongfang.xsltools.xpath2;

public class XPathItemTest extends XPathBase {
  public XPathItemTest(int id) {
    super(id);
  }

  public XPathItemTest(XPathParser p, int id) {
    super(p, id);
  }

  @Override
public String toString() {
    return "item()";
  }
}
