/* Generated By:JJTree: Do not edit this line. XPathFilterExpr.java */

package dongfang.xsltools.xpath2;

import java.util.Iterator;

public interface XPathStepExpr extends XPathExpr, Cloneable {
  boolean hasPredicates();

  Iterator<XPathExpr> predicates(); // ell. l.

  void addEmptyPredicateList();

  Object clone();
}
