/* Generated By:JJTree: Do not edit this line. XPathMultiplicativeExpr.java */

package dongfang.xsltools.xpath2;

public class XPathMultiplicativeExpr extends
    XPathAbstractArtihmeticOperatorExpr implements XPathArithmeticExpr {
  public XPathMultiplicativeExpr(int id) {
    super(id);
  }

  public XPathMultiplicativeExpr(XPathParser p, int id) {
    super(p, id);
  }
}
