/* Generated By:JJTree: Do not edit this line. XPathAbsolutePathExpr.java */

package dongfang.xsltools.xpath2;

/*
 * An absolute path expr, like /foo
 */
public class XPathAbsolutePathExpr extends XPathPathExpr {
  public XPathAbsolutePathExpr() {
    super(0);
  }

  public XPathAbsolutePathExpr(int id) {
    super(id);
  }

  public XPathAbsolutePathExpr(XPathParser p, int id) {
    super(p, id);
  }

  @Override
  public double defaultPriority() {
    // rule 2
    if (getStepCount() == 0)
      return -0.5;
    return 0.5;
  }

  @Override
public String toString() {
    return "/" + super.toString();
  }
}
