/* Generated By:JJTree: Do not edit this line. XPathQuantifiedExpr.java */

package dongfang.xsltools.xpath2;

import dongfang.xsltools.exceptions.XSLToolsException;

public class XPathQuantifiedExpr extends XPathQNameExprBase {
  String quantifier;

  public XPathQuantifiedExpr(int id) {
    super(id);
  }

  public XPathQuantifiedExpr(XPathParser p, int id) {
    super(p, id);
  }

  void setQuantifier(String s) {
    this.quantifier = s;
  }

  public short getType() {
    return TYPE_ANY; // TODO: sharpen
  }

  /*
   * This expression introduces locally scoped variables. Some visitors want to
   * know about that, so we accept them explicitly.
   */
  @Override
  public XPathBase accept(XPathVisitor v) throws XSLToolsException {
    return v.visit(this);
  }

  @Override
public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append(quantifier);
    sb.append(" $");
    sb.append(qname.getQualifiedName());
    sb.append(" in ");
    sb.append(jjtGetChild(0).toString());
    int i;
    for (i = 1; i < jjtGetNumChildren() - 1; i++) {
      sb.append(jjtGetChild(i).toString());
    }
    sb.append(" satisfies ");
    sb.append(jjtGetChild(i).toString());
    return sb.toString();
  }
}
