/* Generated By:JJTree: Do not edit this line. XPathComparisonExpr.java */

package dongfang.xsltools.xpath2;

public class XPathComparisonExpr extends XPathBase implements XPathExpr {
  private String operator;

  public XPathComparisonExpr(int id) {
    super(id);
  }

  public XPathComparisonExpr(XPathParser p, int id) {
    super(p, id);
  }

  void setOperator(String s) {
    this.operator = s;
  }

  public short getType() {
    return TYPE_BOOLEAN;
  }

  public String getOperator() {
    return operator;
  }
  
  public XPathExpr getLHS() {
    return (XPathExpr)jjtGetChild(0);
  }
  
  public XPathExpr getRHS() {
    return (XPathExpr)jjtGetChild(1);
  }

  @Override
public String toString() {
    return jjtGetChild(0).toString() + " " + operator + " "
        + jjtGetChild(1).toString();
  }
}
