/* Generated By:JJTree: Do not edit this line. XPathForExpr.java */

package dongfang.xsltools.xpath2;

import dongfang.xsltools.exceptions.XSLToolsException;

public class XPathForExpr extends XPathQNameExprBase {
  public XPathForExpr(int id) {
    super(id);
  }

  public XPathForExpr(XPathParser p, int id) {
    super(p, id);
  }

  public short getType() {
    return ((XPathExpr) jjtGetChild(jjtGetNumChildren() - 1)).getType();
  }

  /*
   * This expression introduces locally scoped variables. Some visitors want to
   * know about that, so we accept them explicitly.
   */
  @Override
  public XPathBase accept(XPathVisitor v) throws XSLToolsException {
    return v.visit(this);
  }

  @Override
public String toString() {
    StringBuilder res = new StringBuilder();
    res.append("for $");
    res.append(qname.getQualifiedName());
    res.append(" in ");
    res.append(jjtGetChild(0).toString());

    for (int i = 1; i < jjtGetNumChildren() - 1; i++) {
      res.append(jjtGetChild(i).toString());
    }

    res.append(" return ");
    res.append(jjtGetChild(jjtGetNumChildren() - 1).toString());
    return res.toString();
  }
}
