/* Generated By:JJTree: Do not edit this line. XPathCommaExpr.java */

package dongfang.xsltools.xpath2;

public class XPathCommaExpr extends XPathBase implements XPathExpr {
  public XPathCommaExpr(int id) {
    super(id);
  }

  public XPathCommaExpr(XPathParser p, int id) {
    super(p, id);
  }

  public short getType() {
    return TYPE_ANY; // TODO: in fact this is some list type
  }

  @Override
public String toString() {
    StringBuilder res = new StringBuilder();
    boolean needsComma = false;
    for (int i = 0; i < jjtGetNumChildren(); i++) {
      if (needsComma) {
        res.append(',');
      } else
        needsComma = true;
      res.append(jjtGetChild(i)).toString();
    }
    return res.toString();
  }
}
