/* Generated By:JJTree: Do not edit this line. XPathExpr.java */

package dongfang.xsltools.xpath2;

public interface XPathExpr extends IXPathBase {
  short TYPE_ANY = 0;

  short TYPE_STRING = 1;

  short TYPE_BOOLEAN = 2;

  short TYPE_NUM = 3;

  short TYPE_NODELIST = 4;

  short getType();

  void setArtifact(String artifact);
}
