/* Generated By:JJTree: Do not edit this line. XPathAdditiveExpr.java */

package dongfang.xsltools.xpath2;

/*
 * Addition or subtraction. Any arity > 1.
 */

public class XPathAdditiveExpr extends XPathAbstractArtihmeticOperatorExpr
    implements XPathArithmeticExpr {
  public XPathAdditiveExpr(int id) {
    super(id);
  }

  @Override
public short getType() {
    return TYPE_NUM;
  }

  public XPathAdditiveExpr(XPathParser p, int id) {
    super(p, id);
  }
}
