/* Generated By:JJTree: Do not edit this line. XPathForExpr.java */

package dongfang.xsltools.xpath2;

import java.util.Iterator;

public abstract class XPathPredicateCarrier extends XPathBase {
  public XPathPredicateCarrier(int id) {
    super(id);
  }

  public XPathPredicateCarrier(XPathParser p, int id) {
    super(p, id);
  }

  public XPathPredicateList getPredicateList() {
    return (XPathPredicateList) jjtGetChild(jjtGetNumChildren() - 1);
  }

  public boolean hasPredicates() {
    XPathPredicateList pl = getPredicateList();
    return pl.hasPredicates();
  }

  public void addEmptyPredicateList() {
    jjtAddChild(new XPathPredicateList(), jjtGetNumChildren());
  }

  public XPathExpr getPredicate(int i) {
    return getPredicateList().getPredicate(i);
  }

  public Iterator<XPathExpr> predicates() {
    return getPredicateList().predicates();
  }
}
