/* Generated By:JJTree: Do not edit this line. XPathRelativePathExpr.java */

package dongfang.xsltools.xpath2;

public class XPathRelativePathExpr extends XPathPathExpr {
  public XPathRelativePathExpr(int id) {
    super(id);
  }

  public XPathRelativePathExpr(XPathParser p, int id) {
    super(p, id);
  }

  public XPathRelativePathExpr() {
    super(0);
  }
}
