/* Generated By:JJTree: Do not edit this line. XPathQuantifiedExpr2.java */

package dongfang.xsltools.xpath2;

public class XPathQuantifiedExpr2 extends XPathQNameExprBase {
  public XPathQuantifiedExpr2(int id) {
    super(id);
  }

  public XPathQuantifiedExpr2(XPathParser p, int id) {
    super(p, id);
  }

  public short getType() {
    return TYPE_ANY; // TODO: sharpen
  }

  @Override
public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append(",$");
    sb.append(qname.getQualifiedName());
    sb.append(" in ");
    sb.append(jjtGetChild(0).toString());
    return sb.toString();
  }
}
