/* Generated By:JJTree: Do not edit this line. XPathItemTest.java */

package dongfang.xsltools.xpath2;

import java.util.Set;

import dongfang.xsltools.exceptions.XSLToolsSchemaException;
import dongfang.xsltools.xmlclass.schemaside.AttributeUse;
import dongfang.xsltools.xmlclass.schemaside.ElementUse;
import dongfang.xsltools.xmlclass.schemaside.SingleTypeXMLClass;
import dongfang.xsltools.xmlclass.xslside.CommentNT;
import dongfang.xsltools.xmlclass.xslside.PINT;
import dongfang.xsltools.xmlclass.xslside.RootNT;
import dongfang.xsltools.xmlclass.xslside.TextNT;
import dongfang.xsltools.xmlclass.xslside.UndeclaredNodeType;

public abstract class XPathNodeTest extends XPathBase {

  public XPathNodeTest(int id) {
    super(id);
  }

  public XPathNodeTest(XPathParser p, int id) {
    super(p, id);
  }

  public abstract Set<UndeclaredNodeType> etest(Set<UndeclaredNodeType> delta);

  public Set<UndeclaredNodeType> atest(Set<UndeclaredNodeType> delta) {
    return etest(delta);
  }

  public abstract boolean accept(ElementUse nt, SingleTypeXMLClass clazz)
      throws XSLToolsSchemaException;

  public abstract boolean accept(AttributeUse nt, SingleTypeXMLClass clazz)
      throws XSLToolsSchemaException;

  abstract boolean accept(CommentNT nt);

  abstract boolean accept(PINT nt);

  abstract boolean accept(RootNT nt, SingleTypeXMLClass clazz);

  abstract boolean accept(TextNT nt);

  public abstract String testAttributeAxisRegExp(SingleTypeXMLClass clazz)
      throws XSLToolsSchemaException;

  public abstract String testSDOSAxisRegExp(SingleTypeXMLClass clazz)
      throws XSLToolsSchemaException;

  public abstract String testCDAxisRegExp(SingleTypeXMLClass clazz)
      throws XSLToolsSchemaException;
}
