/* Generated By:JJTree: Do not edit this line. XPathAnyNodeTest.java */

package dongfang.xsltools.xpath2;

import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;

public abstract class XPathAbstractArtihmeticOperatorExpr extends XPathBase
    implements XPathExpr {
  private List<String> operators = new LinkedList<String>();

  public XPathAbstractArtihmeticOperatorExpr(int id) {
    super(id);
  }

  public XPathAbstractArtihmeticOperatorExpr(XPathParser p, int id) {
    super(p, id);
  }

  void addOperator(String s) {
    operators.add(s);
  }

  public short getType() {
    return TYPE_NUM;
  }

  @Override
public String toString() {
    StringBuilder sb = new StringBuilder();
    boolean needsOperator = false;
    Iterator<String> operators = this.operators.iterator();
    for (int i = 0; i < jjtGetNumChildren(); i++) {
      if (needsOperator) {
        sb.append(' ');
        sb.append(operators.next());
        sb.append(' ');
      } else
        needsOperator = true;
      sb.append(jjtGetChild(i).toString());
    }
    return sb.toString();
  }
}
