/* Generated By:JJTree: Do not edit this line. XPathIntersectExceptExpr.java */

package dongfang.xsltools.xpath2;

import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;

public class XPathIntersectExceptExpr extends XPathBase implements XPathExpr {
  List<String> operators = new LinkedList<String>();

  public XPathIntersectExceptExpr(int id) {
    super(id);
  }

  public XPathIntersectExceptExpr(XPathParser p, int id) {
    super(p, id);
  }

  void addOperator(String operator) {
    this.operators.add(operator);
  }

  public short getType() {
    return TYPE_ANY;
  }

  @Override
public String toString() {
    StringBuilder res = new StringBuilder();
    boolean needsOper = false;
    Iterator<String> operators = this.operators.iterator();
    for (int i = 0; i < jjtGetNumChildren(); i++) {
      if (needsOper) {
        res.append(' ');
        res.append(operators.next());
        res.append(' ');
      } else
        needsOper = true;
      res.append(jjtGetChild(i).toString());
    }
    return res.toString();
  }
}
