/* Generated By:JJTree: Do not edit this line. XPathCastExpr.java */

package dongfang.xsltools.xpath2;

public class XPathCastExpr extends XPathBase implements XPathExpr {
  public XPathCastExpr(int id) {
    super(id);
  }

  public XPathCastExpr(XPathParser p, int id) {
    super(p, id);
  }

  public short getType() {
    return TYPE_ANY; // TODO: sharpen up
  }

  @Override
public String toString() {
    String res = jjtGetChild(0).toString();
    if (jjtGetNumChildren() > 1) {
      res += " cast as " + jjtGetChild(1).toString();
    }
    return res;
  }
}
