/* Generated By:JJTree: Do not edit this line. XPathUnionExp.java */

package dongfang.xsltools.xpath2;

import java.util.Iterator;

public class XPathUnionExpr extends XPathBase implements XPathExpr,
    Iterable<XPathExpr> {
  public XPathUnionExpr(int id) {
    super(id);
  }

  public XPathUnionExpr(XPathParser p, int id) {
    super(p, id);
  }

  public XPathUnionExpr() {
    this(0);
  }

  public void add(XPathBase sub) {
    jjtAddChild(sub, jjtGetNumChildren());
  }

  public Iterator<XPathExpr> iterator() {
    return new Iterator<XPathExpr>() {
      int i = 0;

      public boolean hasNext() {
        // TODO Auto-generated method stub
        return i < jjtGetNumChildren();
      }

      public XPathExpr next() {
        // TODO Auto-generated method stub
        return (XPathExpr) jjtGetChild(i++);
      }

      public void remove() {
      }
    };
  }

  public short getType() {
    return TYPE_NODELIST;
  }

  @Override
public String toString() {
    StringBuilder res = new StringBuilder();
    boolean needsUnion = false;
    for (int i = 0; i < jjtGetNumChildren(); i++) {
      if (needsUnion)
        res.append(" | ");
      else
        needsUnion = true;
      res.append(jjtGetChild(i).toString());
    }
    return res.toString();
  }
}
