/* Generated By:JJTree: Do not edit this line. XPathTextTest.java */

package dongfang.xsltools.xpath2;

import java.util.Set;

import dongfang.xsltools.exceptions.XSLToolsSchemaException;
import dongfang.xsltools.xmlclass.CharGenerator;
import dongfang.xsltools.xmlclass.schemaside.AttributeUse;
import dongfang.xsltools.xmlclass.schemaside.ElementUse;
import dongfang.xsltools.xmlclass.schemaside.SingleTypeXMLClass;
import dongfang.xsltools.xmlclass.xslside.CommentNT;
import dongfang.xsltools.xmlclass.xslside.PINT;
import dongfang.xsltools.xmlclass.xslside.RootNT;
import dongfang.xsltools.xmlclass.xslside.TextNT;
import dongfang.xsltools.xmlclass.xslside.UndeclaredNodeType;

public class XPathTextTest extends XPathNodeTest {
  public XPathTextTest(int id) {
    super(id);
  }

  public XPathTextTest(XPathParser p, int id) {
    super(p, id);
  }

  public XPathTextTest() {
    super(0);
  }

  @Override
public Set<UndeclaredNodeType> etest(Set<UndeclaredNodeType> delta) {
    boolean hasComment = delta.contains(TextNT.chameleonInstance);
    delta.clear();
    if (hasComment)
      delta.add(TextNT.chameleonInstance);
    return delta;
  }

  @Override
  public boolean accept(AttributeUse nt, SingleTypeXMLClass clazz) {
    return false;
  }

  @Override
  boolean accept(CommentNT nt) {
    return false;
  }

  @Override
  public boolean accept(ElementUse nt, SingleTypeXMLClass clazz) {
    return false;
  }

  @Override
  boolean accept(PINT nt) {
    return false;
  }

  @Override
  boolean accept(RootNT nt, SingleTypeXMLClass clazz) {
    return false;
  }

  @Override
  boolean accept(TextNT nt) {
    return true;
  }

  @Override
  public String testAttributeAxisRegExp(SingleTypeXMLClass clazz)
      throws XSLToolsSchemaException {
    return "" + CharGenerator.getAbsurdChar();
  }

  @Override
  public String testSDOSAxisRegExp(SingleTypeXMLClass clazz)
      throws XSLToolsSchemaException {
    return "" + TextNT.chameleonInstance.getCharRepresentation(clazz);
  }

  @Override
  public String testCDAxisRegExp(SingleTypeXMLClass clazz)
      throws XSLToolsSchemaException {
    return "" + TextNT.chameleonInstance.getCharRepresentation(clazz);
  }

  @Override
public String toString() {
    return "text()";
  }
}
