/* Generated By:JJTree: Do not edit this line. src/dongfang/xsltools/xpath2/XPathParserTreeConstants.java */

package dongfang.xsltools.xpath2;

public interface XPathParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTCOMMAEXPR = 1;
  public int JJTFOREXPR = 2;
  public int JJTSIMPLEFORCLAUSE2 = 3;
  public int JJTQUANTIFIEDEXPR = 4;
  public int JJTQUANTIFIEDEXPR2 = 5;
  public int JJTIFEXPR = 6;
  public int JJTOREXPR = 7;
  public int JJTANDEXPR = 8;
  public int JJTCOMPARISONEXPR = 9;
  public int JJTRANGEEXPR = 10;
  public int JJTADDITIVEEXPR = 11;
  public int JJTMULTIPLICATIVEEXPR = 12;
  public int JJTUNIONEXPR = 13;
  public int JJTINTERSECTEXCEPTEXPR = 14;
  public int JJTINSTANCEOFEXPR = 15;
  public int JJTTREATASEXPR = 16;
  public int JJTCASTABLEEXPR = 17;
  public int JJTCASTEXPR = 18;
  public int JJTUNARYEXPR = 19;
  public int JJTABSOLUTEPATHEXPR = 20;
  public int JJTFUNCTIONCALLEXPR = 21;
  public int JJTAXISSTEP = 22;
  public int JJTNAMETEST = 23;
  public int JJTRELATIVEPATHEXPR = 24;
  public int JJTANYNODETEST = 25;
  public int JJTVARREF = 26;
  public int JJTPARENTHESIZEDEXPR = 27;
  public int JJTPREDICATELIST = 28;
  public int JJTSINGLETYPE = 29;
  public int JJTEMPTYSEQUENCETYPE = 30;
  public int JJTITEMTYPE = 31;
  public int JJTITEMTEST = 32;
  public int JJTDOCUMENTTEST = 33;
  public int JJTTEXTTEST = 34;
  public int JJTCOMMENTTEST = 35;
  public int JJTPITEST = 36;
  public int JJTSCHEMAATTRIBUTETEST = 37;
  public int JJTELEMENTTEST = 38;
  public int JJTATTRIBUTETEST = 39;
  public int JJTSCHEMAELEMENTTEST = 40;
  public int JJTNUMERICLITERAL = 41;
  public int JJTSTRINGLITERAL = 42;


  public String[] jjtNodeName = {
    "void",
    "CommaExpr",
    "ForExpr",
    "SimpleForClause2",
    "QuantifiedExpr",
    "QuantifiedExpr2",
    "IfExpr",
    "OrExpr",
    "AndExpr",
    "ComparisonExpr",
    "RangeExpr",
    "AdditiveExpr",
    "MultiplicativeExpr",
    "UnionExpr",
    "IntersectExceptExpr",
    "InstanceOfExpr",
    "TreatAsExpr",
    "CastableExpr",
    "CastExpr",
    "UnaryExpr",
    "AbsolutePathExpr",
    "FunctionCallExpr",
    "AxisStep",
    "NameTest",
    "RelativePathExpr",
    "AnyNodeTest",
    "VarRef",
    "ParenthesizedExpr",
    "PredicateList",
    "SingleType",
    "EmptySequenceType",
    "ItemType",
    "ItemTest",
    "DocumentTest",
    "TextTest",
    "CommentTest",
    "PITest",
    "SchemaAttributeTest",
    "ElementTest",
    "AttributeTest",
    "SchemaElementTest",
    "NumericLiteral",
    "StringLiteral",
  };
}
