/* Generated By:JJTree: Do not edit this line. XPathNumericLiteral.java */

package dongfang.xsltools.xpath2;

public class XPathNumericLiteral extends XPathPredicateCarrier implements
    XPathFilterExpr {
  private String content;

  public XPathNumericLiteral(int id) {
    super(id);
  }

  public XPathNumericLiteral(XPathParser p, int id) {
    super(p, id);
  }

  public XPathNumericLiteral() {
    this(0);
  }

  void setContent(String s) {
    this.content = s;
  }

  public short getType() {
    return TYPE_NUM;
  }

  @Override
public String toString() {
    return content;
  }
}
