/* Generated By:JJTree: Do not edit this line. XPathInstanceOfExpr.java */

package dongfang.xsltools.xpath2;

public class XPathInstanceOfExpr extends XPathBase implements XPathExpr {
  public XPathInstanceOfExpr(int id) {
    super(id);
  }

  public XPathInstanceOfExpr(XPathParser p, int id) {
    super(p, id);
  }

  public short getType() {
    return TYPE_BOOLEAN;
  }

  @Override
public String toString() {
    StringBuilder res = new StringBuilder();
    res.append(jjtGetChild(0).toString());
    if (jjtGetNumChildren() > 1) {
      res.append(" instance of ");
      res.append(jjtGetChild(1).toString());
    }
    return res.toString();
  }
}
