/* Generated By:JJTree: Do not edit this line. XPathAndExpr.java */

package dongfang.xsltools.xpath2;

/*
 * And expr; is a Logical Expression
 */
public class XPathAndExpr extends XPathLogicalExpr {
  public XPathAndExpr(int id) {
    super(id);
  }

  public XPathAndExpr(XPathParser p, int id) {
    super(p, id);
  }

  @Override
String getOperatorName() {
    return "and";
  }
}
