/* Generated By:JJTree: Do not edit this line. XPathIfExpr.java */

package dongfang.xsltools.xpath2;

public class XPathIfExpr extends XPathBase implements XPathExpr {
  public XPathIfExpr(int id) {
    super(id);
  }

  public XPathIfExpr(XPathParser p, int id) {
    super(p, id);
  }

  public short getType() {
    short t1 = ((XPathExpr) jjtGetChild(1)).getType();
    short t2 = ((XPathExpr) jjtGetChild(1)).getType();
    if (t1 == t2)
      return t1;
    return TYPE_ANY;
  }

  @Override
public String toString() {
    StringBuilder res = new StringBuilder();
    res.append("if (");
    res.append(jjtGetChild(0).toString());
    res.append(") then ");
    res.append(jjtGetChild(1).toString());
    res.append(" else ");
    res.append(jjtGetChild(2).toString());
    return res.toString();
  }
}
