/* Generated By:JJTree: Do not edit this line. XPathEmptySequenceType.java */

package dongfang.xsltools.xpath2;

public class XPathEmptySequenceType extends XPathBase {
  public XPathEmptySequenceType(int id) {
    super(id);
  }

  public XPathEmptySequenceType(XPathParser p, int id) {
    super(p, id);
  }

  @Override
public String toString() {
    return "empty-sequence()";
  }
}
