/* Generated By:JJTree: Do not edit this line. XPathOrExpr.java */

package dongfang.xsltools.xpath2;

public class XPathOrExpr extends XPathLogicalExpr {
  public XPathOrExpr(int id) {
    super(id);
  }

  public XPathOrExpr(XPathParser p, int id) {
    super(p, id);
  }

  @Override
String getOperatorName() {
    return "or";
  }
}
