/* Generated By:JJTree: Do not edit this line. XPathAnyNodeTest.java */

package dongfang.xsltools.xpath2;

import java.util.Set;

import dongfang.xsltools.exceptions.XSLToolsSchemaException;
import dongfang.xsltools.xmlclass.schemaside.AttributeUse;
import dongfang.xsltools.xmlclass.schemaside.ElementUse;
import dongfang.xsltools.xmlclass.schemaside.SingleTypeXMLClass;
import dongfang.xsltools.xmlclass.xslside.CommentNT;
import dongfang.xsltools.xmlclass.xslside.PINT;
import dongfang.xsltools.xmlclass.xslside.RootNT;
import dongfang.xsltools.xmlclass.xslside.TextNT;
import dongfang.xsltools.xmlclass.xslside.UndeclaredNodeType;

public class XPathAnyNodeTest extends XPathNodeTest {
  public XPathAnyNodeTest(int id) {
    super(id);
  }

  public XPathAnyNodeTest(XPathParser p, int id) {
    super(p, id);
  }

  public XPathAnyNodeTest() {
    this(0);
  }

  @Override
public Set<UndeclaredNodeType> etest(Set<UndeclaredNodeType> delta) {
    return delta;
  }

  @Override
  public boolean accept(AttributeUse nt, SingleTypeXMLClass clazz) {
    return true;
  }

  @Override
  boolean accept(CommentNT nt) {
    return true;
  }

  @Override
  public boolean accept(ElementUse nt, SingleTypeXMLClass clazz) {
    return true;
  }

  @Override
  boolean accept(PINT nt) {
    return true;
  }

  @Override
  boolean accept(RootNT nt, SingleTypeXMLClass clazz) {
    return true;
  }

  @Override
  boolean accept(TextNT nt) {
    return true;
  }

  @Override
  public String testAttributeAxisRegExp(SingleTypeXMLClass clazz)
      throws XSLToolsSchemaException {
    return clazz.getAttributeRegExp();
  }

  @Override
  public String testSDOSAxisRegExp(SingleTypeXMLClass clazz)
      throws XSLToolsSchemaException {
    return ".";
  }

  @Override
  public String testCDAxisRegExp(SingleTypeXMLClass clazz)
      throws XSLToolsSchemaException {
    return "(" + clazz.getElementRegExp() + "|"
        + TextNT.chameleonInstance.getCharRepresentation(clazz) + "|"
        + CommentNT.instance.getCharRepresentation(clazz) + "|"
        + PINT.chameleonInstance.getCharRepresentation(clazz) + ")";
  }

  @Override
public String toString() {
    return "node()";
  }
}
